In [1]:
import numpy as np
import matplotlib.pyplot as plt
import skimage as skimage
import math
%matplotlib inline
from skimage import color
import scipy.ndimage
import scipy.stats
import scipy.spatial.distance as dist
import scipy.optimize
from scipy.optimize import curve_fit
import random
import pickle
from tqdm import tqdm
import pandas as pd

### Load excel data

In [2]:
df =pd.read_csv('data\orientationdata\point_data_all_xsection3.csv')
#df = df.iloc[:, 0].str.split(',', expand=True)
df.columns = ['X', 'Y','Z','formation']
df

            X     Y           Z              formation
0      0.0000  2000 -130.942031                   topo
1    119.8392  2000 -112.101451                   topo
2    167.4676  2000  -91.376813                   topo
3    215.0960  2000  -81.956523                   topo
4    255.0424  2000  -74.420291                   topo
..        ...   ...         ...                    ...
56   792.7824  2000 -758.333345  questagraniteporphyry
57   929.5220  2000 -749.855084  questagraniteporphyry
58   998.6600  2000 -752.681171  questagraniteporphyry
59  1153.8364  2000 -766.811606  questagraniteporphyry
60  1222.9744  2000 -780.000012  questagraniteporphyry

[61 rows x 4 columns]

### Additional Dimentions

In [3]:
#add dip
df.loc[:, 'dip'] = '0'

#add azimuth
df.loc[:, 'azimuth'] = '90'

#add polarity
df.loc[:, 'polarity'] = '1'

df = df[['X', 'Y', 'Z','dip','azimuth','polarity','formation']]


df

            X     Y           Z dip azimuth polarity              formation
0      0.0000  2000 -130.942031   0      90        1                   topo
1    119.8392  2000 -112.101451   0      90        1                   topo
2    167.4676  2000  -91.376813   0      90        1                   topo
3    215.0960  2000  -81.956523   0      90        1                   topo
4    255.0424  2000  -74.420291   0      90        1                   topo
..        ...   ...         ...  ..     ...      ...                    ...
56   792.7824  2000 -758.333345   0      90        1  questagraniteporphyry
57   929.5220  2000 -749.855084   0      90        1  questagraniteporphyry
58   998.6600  2000 -752.681171   0      90        1  questagraniteporphyry
59  1153.8364  2000 -766.811606   0      90        1  questagraniteporphyry
60  1222.9744  2000 -780.000012   0      90        1  questagraniteporphyry

[61 rows x 7 columns]

In [4]:
#save the data at the end
df.to_csv(r'data\orientationdata\orientation_data_xsection3.csv', index = False)