In [13]:
import numpy as np
import matplotlib.pyplot as plt
import skimage as skimage
import math
%matplotlib inline
from skimage import color
import scipy.ndimage
import scipy.stats
import scipy.spatial.distance as dist
import scipy.optimize
from scipy.optimize import curve_fit
import random
import pickle
from tqdm import tqdm
import pandas as pd

### Load excel data

In [14]:
df =pd.read_csv('data\orientationdata\initial data.csv')
#df = df.iloc[:, 0].str.split(',', expand=True)
df.columns = ['X', 'Y','Z','formation']
df

       X  Y     Z               formation
0    424  0 -1412  Equigranular Monzonite
1    472  0 -1284  Equigranular Monzonite
2    525  0 -1139  Equigranular Monzonite
3    622  0  -969  Equigranular Monzonite
4    640  0  -930  Equigranular Monzonite
..   ... ..   ...                     ...
68   820  0 -1337                baserock
69   885  0 -1272                baserock
70   991  0 -1250                baserock
71  1084  0 -1279                baserock
72  1113  0 -1337                baserock

[73 rows x 4 columns]

### Additional Dimentions

In [15]:
#add dip
df.loc[:, 'dip'] = '0'

#add azimuth
df.loc[:, 'azimuth'] = '0'

#add polarity
df.loc[:, 'polarity'] = '0'

df = df[['X', 'Y', 'Z','dip','azimuth','polarity','formation']]


df

       X  Y     Z dip azimuth polarity               formation
0    424  0 -1412   0       0        0  Equigranular Monzonite
1    472  0 -1284   0       0        0  Equigranular Monzonite
2    525  0 -1139   0       0        0  Equigranular Monzonite
3    622  0  -969   0       0        0  Equigranular Monzonite
4    640  0  -930   0       0        0  Equigranular Monzonite
..   ... ..   ...  ..     ...      ...                     ...
68   820  0 -1337   0       0        0                baserock
69   885  0 -1272   0       0        0                baserock
70   991  0 -1250   0       0        0                baserock
71  1084  0 -1279   0       0        0                baserock
72  1113  0 -1337   0       0        0                baserock

[73 rows x 7 columns]

In [16]:
#save the data at the end
df.to_csv(r'data\orientationdata\orientation_data.csv', index = False)